name: Continuous Integration

# This workflow is triggered whenever a new PR is created on the main branch
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
permissions: read-all
jobs:
  # Run unit tests to make sure everything is 👍
  test:
    name: "Run unit tests"
    defaults:
      run:
        shell: bash
        
    # Specify the OS we want the workflow to run on
    runs-on: ubuntu-latest
    # Define the steps for this job
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        name: "Checkout repository"

      - name: "Install Dependencies"
        run: npm install

      - name: "Run Tests"
        run: npm test

  # Run the linter to check for code style issues
  lint:
    name: "Run linter"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        name: "Checkout repository"

      - name: "Install Dependencies"
        run: npm install

      - name: "Run Linter"
        run: npx eslint 'src/**'
